### ISSUE TITLE
Hide / Close / Acknowledge errors

### ISSUE THREAD

**Issue by zedalaye** [BaseSecrete/rorvswild#3]
Is there a way to acknowledge errors (to make errors disappear) in RorVsWild WebUI ?

**Comment by alexisbernard** [comment]
No there is no such button because the approch is different. Errors are ordered by last occurence. The latest active are at the top. Errors that are fixed mechanically go to the bottom of the list and then disappear since they are filtered by date.

However if you need to ignore some types of exception just do the following:

```yaml
# config/rorvswild.yml
production:
  api_key: API_KEY
  ignored_exceptions:
    - ActionController::RoutingError
    - ZeroDivisionError
```

```ruby
# config/initializers/rorvswild.rb
RorVsWild::Client.new(
  api_key: "API_KEY",
  ignored_exceptions: ["ActionController::RoutingError", "ZeroDivisionError"])
```
